try{
    let a = 2 + b;
}catch(error){
    console.log("Deu o seguinte error " + error);
}finally{
    console.log("Executou"); 
}
